HIPC Lyoplate geo data
-----------------------

```{r load-libraries}
library(ggplot2)
library(ggmap)
library(mapdata)
library(mapproj)
library(RgoogleMaps)
library(grid)
#Set some knitr options
opts_knit$set(progress = TRUE, verbose = TRUE)
opts_chunk$set(cache=FALSE, fig.width=12, echo=TRUE, eval=TRUE, message=TRUE, warning=TRUE)
```

```{r read-center-info}
centers<-read.csv("centers.csv")
```

```{r uk-map}
#load us map data
png("../figures/HIPC-uk-map.png",bg="transparent",width=720,height=720,pointsize=16)
map <- get_map(location="manchester",maptype = "roadmap", source="google",zoom=6,color="bw")
p<-ggmap(map)+opts(panel.grid.major=theme_blank(),panel.grid.minor=theme_blank(),axis.text.y = theme_blank(),axis.ticks=theme_blank(),axis.text.x = theme_blank(),axis.title.x = theme_blank(),axis.title.y = theme_blank(),legend.position = "none",plot.background = theme_rect(fill = "transparent",colour = NA),plot.margin = unit(c(0,0,-1,-1), "lines"))
p+geom_point(data=centers, aes(x=long, y=lat,color=HIPC),alpha=.9,size=5)+ geom_text( data=centers, hjust=0.5, vjust=-1, aes(x=long, y=lat, label=Center,color=HIPC), size=7,alpha=1)+scale_color_manual(values = c("#1F78B4","#E31A1C"))
dev.off()
```

```{r usa-map}
png("../figures/HIPC-usa-map.png",bg="transparent",width=720,height=720,pointsize=16)
#load us map data
map <- get_map(location="kansas",maptype = "roadmap", source="google",zoom=4,color="bw")
p<-ggmap(map)+opts(panel.grid.major=theme_blank(),panel.grid.minor=theme_blank(),axis.text.y = theme_blank(),axis.ticks=theme_blank(),axis.text.x = theme_blank(),axis.title.x = theme_blank(),axis.title.y = theme_blank(),legend.position = "none",plot.background = theme_rect(fill = "transparent",colour = NA),plot.margin = unit(c(0,0,-1,-1), "lines"))
p+geom_point(data=centers, aes(x=long, y=lat,color=HIPC),alpha=.9,size=5)+ geom_text( data=centers, hjust=0.5, vjust=-1, aes(x=long, y=lat, label=Center,color=HIPC), size=7,alpha=1)+scale_color_manual(values = c("#1F78B4","#E31A1C"))
dev.off()
```


